language: perl
sudo: false

addons:
  apt:
    packages:
      libmicrohttpd-dev

install:
  - perlbrew list
  - sh corpus/install_alien_builder
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

script:
  - dzil test -v

env:
  - ALIEN_INSTALL_TYPE=system
  - ALIEN_INSTALL_TYPE=share
